name: Publish to forgebox
# you may wish to trigger this for other specifics, this is an example
on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish to forgebox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: releasenumber
        uses: pixl8/github-action-twgit-release-version-generator@master

      - uses: pixl8/github-action-build-preside-extension

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ${{ env.PACKAGE_ZIP }}
          asset_name: ${{ env.RELEASE_NUMBER }}.zip
          asset_content_type: application/zip

      # - uses: pixl8/box-publish-github-action@master
      #   env:
      #     FORGEBOX_USER: pixl8
      #     FORGEBOX_PASS: ${{ secrets.FORGEBOX_PASS }}